
[[constraint]]
  name = "github.com/coredns/coredns"
  version = "1.2.6"

[[constraint]]
  name = "jw4.us/nspub"
  branch = "master"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[override]]
  name = "github.com/apache/thrift"
  revision = "e59b73d3c2bf1c328ccb78e683c0462fa1a473c7"

[prune]
  go-tests = true
  unused-packages = true
