
[[constraint]]
  name = "github.com/coredns/coredns"
  version = "1.3.0"

[[constraint]]
  name = "jw4.us/nspub"
  branch = "master"

[[override]]
  name = "github.com/mholt/caddy"
  version = "v0.11.1"

[[override]]
  name = "github.com/miekg/dns"
  version = "v1.1.1"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.1"

[[override]]
  name = "github.com/apache/thrift"
  revision = "e59b73d3c2bf1c328ccb78e683c0462fa1a473c7"

[prune]
  go-tests = true
  unused-packages = true
